// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":false,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"SRD_PKM_TrainerSprite","status":true,"description":"Pokemon Plugin: Adds trainer sprites for both male and female independent of the party members.","parameters":{"Initial Gender":"male","=== Male ===":"","Male Char Name":"FRLG Peds1","Male Char Index":"0","M Dash Char Name":"","M Dash Char Index":"","=== Female ===":"","Female Char Name":"Actor2","Female Char Index":"3","F Dash Char Name":"","F Dash Char Index":""}}
];
